hymns = {
                                                           1: ["The Morning Breaks","https://www.churchofjesuschrist.org/music/library/hymns/the-morning-breaks?lang=eng&#39"],
                                                             2: ["The Spirit of God","https://www.churchofjesuschrist.org/music/library/hymns/the-spirit-of-god?lang=eng&#39"],
                                                           3: ["Now Let Us Rejoice","https://www.churchofjesuschrist.org/music/library/hymns/now-let-us-rejoice?lang=eng&#39"],
                                                                     4: ["Truth Eternal","https://www.churchofjesuschrist.org/music/library/hymns/truth-eternal?lang=eng&#39"],
                                               5: ["High on the Mountain Top","https://www.churchofjesuschrist.org/music/library/hymns/high-on-the-mountain-top?lang=eng&#39"],
                                                           6: ["Redeemer of Israel","https://www.churchofjesuschrist.org/music/library/hymns/redeemer-of-israel?lang=eng&#39"],
                                     7: ["Israel, Israel, God Is Calling","https://www.churchofjesuschrist.org/music/library/hymns/israel-israel-god-is-calling?lang=eng&#39"],
                                                                 8: ["Awake and Arise","https://www.churchofjesuschrist.org/music/library/hymns/awake-and-arise?lang=eng&#39"],
                                                                      9: ["Come, Rejoice","https://www.churchofjesuschrist.org/music/library/hymns/come-rejoice?lang=eng&#39"],
                                                   10: ["Come, Sing to the Lord","https://www.churchofjesuschrist.org/music/library/hymns/come-sing-to-the-lord?lang=eng&#39"],
                           11: ["What Was Witnessed in the Heavens?","https://www.churchofjesuschrist.org/music/library/hymns/what-was-witnessed-in-the-heavens?lang=eng&#39"],
                        12: ["What was Witnessed in the Morning Sky","https://www.churchofjesuschrist.org/music/library/hymns/twas-witnessed-in-the-morning-sky?lang=eng&#39"],
                                                    13: ["An Angel from on High","https://www.churchofjesuschrist.org/music/library/hymns/an-angel-from-on-high?lang=eng&#39"],
                      14: ["Sweet Is the Peace the Gospel Brings","https://www.churchofjesuschrist.org/music/library/hymns/sweet-is-the-peace-the-gospel-brings?lang=eng&#39"],
                                              15: ["I Saw a Mighty Angel Fly","https://www.churchofjesuschrist.org/music/library/hymns/i-saw-a-mighty-angel-fly?lang=eng&#39"],
                    16: ["What Glorious Scenes Mine Eyes Behold","https://www.churchofjesuschrist.org/music/library/hymns/what-glorious-scenes-mine-eyes-behold?lang=eng&#39"],
                                   17: ["Awake, Ye Saints of God, Awake!","https://www.churchofjesuschrist.org/music/library/hymns/awake-ye-saints-of-god-awake?lang=eng&#39"],
                                18: ["The Voice of God Again Is Heard","https://www.churchofjesuschrist.org/music/library/hymns/the-voice-of-god-again-is-heard?lang=eng&#39"],
                          19: ["We Thank Thee, O God, for a Prophet","https://www.churchofjesuschrist.org/music/library/hymns/we-thank-thee-o-god-for-a-prophet?lang=eng&#39"],
                                           20: ["God of Power, God of Right","https://www.churchofjesuschrist.org/music/library/hymns/god-of-power-god-of-right?lang=eng&#39"],
                              21: ["Come, Listen to a Prophet's Voice","https://www.churchofjesuschrist.org/music/library/hymns/come-listen-to-a-prophets-voice?lang=eng&#39"],
                                   22: ["We Listen to a Prophet's Voice","https://www.churchofjesuschrist.org/music/library/hymns/we-listen-to-a-prophets-voice?lang=eng&#39"],
                                                    23: ["We Ever Pray for Thee","https://www.churchofjesuschrist.org/music/library/hymns/we-ever-pray-for-thee?lang=eng&#39"],
                                          24: ["God Bless Our Prophet Dear","https://www.churchofjesuschrist.org/music/library/hymns/god-bless-our-prophet-dear?lang=eng&#39"],
                                   25: ["Now We'll Sing with One Accord","https://www.churchofjesuschrist.org/music/library/hymns/now-well-sing-with-one-accord?lang=eng&#39"],
                                         26: ["Joseph Smith's First Prayer","https://www.churchofjesuschrist.org/music/library/hymns/joseph-smiths-first-prayer?lang=eng&#39"],
                                                            27: ["Praise to the Man","https://www.churchofjesuschrist.org/music/library/hymns/praise-to-the-man?lang=eng&#39"],
                               28: ["Saints, Behold How Great Jehovah","https://www.churchofjesuschrist.org/music/library/hymns/saints-behold-how-great-jehovah?lang=eng&#39"],
                                    29: ["A Poor Wayfaring Man of Grief","https://www.churchofjesuschrist.org/music/library/hymns/a-poor-wayfaring-man-of-grief?lang=eng&#39"],
                                                      30: ["Come, Come, Ye Saints","https://www.churchofjesuschrist.org/music/library/hymns/come-come-ye-saints?lang=eng&#39"],
                                       31: ["O God, Our Help in Ages Past","https://www.churchofjesuschrist.org/music/library/hymns/o-god-our-help-in-ages-past?lang=eng&#39"],
                                  32: ["The Happy Day at Last Has Come","https://www.churchofjesuschrist.org/music/library/hymns/the-happy-day-at-last-has-come?lang=eng&#39"],
                                            33: ["Our Mountain Home So Dear","https://www.churchofjesuschrist.org/music/library/hymns/our-mountain-home-so-dear?lang=eng&#39"],
                                                        34: ["O Ye Mountains High","https://www.churchofjesuschrist.org/music/library/hymns/o-ye-mountains-high?lang=eng&#39"],
                                    35: ["For the Strength of the Hills","https://www.churchofjesuschrist.org/music/library/hymns/for-the-strength-of-the-hills?lang=eng&#39"],
                               36: ["They, the Builders of the Nation","https://www.churchofjesuschrist.org/music/library/hymns/they-the-builders-of-the-nation?lang=eng&#39"],
                 37: ["The Wintry Day, Descending to Its Close","https://www.churchofjesuschrist.org/music/library/hymns/the-wintry-day-descending-to-its-close?lang=eng&#39"],
                                         38: ["Come, All Ye Saints of Zion","https://www.churchofjesuschrist.org/music/library/hymns/come-all-ye-saints-of-zion?lang=eng&#39"],
                                                              39: ["O Saints of Zion","https://www.churchofjesuschrist.org/music/library/hymns/o-saints-of-zion?lang=eng&#39"],
                                                   40: ["Arise, O Glorious Zion","https://www.churchofjesuschrist.org/music/library/hymns/arise-o-glorious-zion?lang=eng&#39"],
                                        41: ["Let Zion in Her Beauty Rise","https://www.churchofjesuschrist.org/music/library/hymns/let-zion-in-her-beauty-rise?lang=eng&#39"],
    42: ["Hail to the Brightness of Zion's Glad Morning!","https://www.churchofjesuschrist.org/music/library/hymns/hail-to-the-brightness-of-zions-glad-morning?lang=eng&#39"],
                            43: ["Zion Stands with Hills Surrounded","https://www.churchofjesuschrist.org/music/library/hymns/zion-stands-with-hills-surrounded?lang=eng&#39"],
                                         44: ["Beautiful Zion, Built Above","https://www.churchofjesuschrist.org/music/library/hymns/beautiful-zion-built-above?lang=eng&#39"],
                                            45: ["Lead Me into Life Eternal","https://www.churchofjesuschrist.org/music/library/hymns/lead-me-into-life-eternal?lang=eng&#39"],
                          46: ["Glorious Things of Thee Are Spoken","https://www.churchofjesuschrist.org/music/library/hymns/glorious-things-of-thee-are-spoken?lang=eng&#39"],
                                                      47: ["We Will Sing of Zion","https://www.churchofjesuschrist.org/music/library/hymns/we-will-sing-of-zion?lang=eng&#39"],
                              48: ["Glorious Things Are Sung of Zion","https://www.churchofjesuschrist.org/music/library/hymns/glorious-things-are-sung-of-zion?lang=eng&#39"],
                                                                49: ["Adam-ondi-Ahman","https://www.churchofjesuschrist.org/music/library/hymns/adam-ondi-ahman?lang=eng&#39"],
                           50: ["Come, Thou Glorious Day of Promise","https://www.churchofjesuschrist.org/music/library/hymns/come-thou-glorious-day-of-promise?lang=eng&#39"],
                                   51: ["Sons of Michael, He Approaches","https://www.churchofjesuschrist.org/music/library/hymns/sons-of-michael-he-approaches?lang=eng&#39"],
                                              52: ["The Day Dawn Is Breaking","https://www.churchofjesuschrist.org/music/library/hymns/the-day-dawn-is-breaking?lang=eng&#39"],
                                 53: ["Let Earth's Inhabitants Rejoice","https://www.churchofjesuschrist.org/music/library/hymns/let-earths-inhabitants-rejoice?lang=eng&#39"],
                               54: ["Behold, the Mountain of the Lord","https://www.churchofjesuschrist.org/music/library/hymns/behold-the-mountain-of-the-lord?lang=eng&#39"],
                                      55: ["Lo, the Mighty God Appearing!","https://www.churchofjesuschrist.org/music/library/hymns/lo-the-mighty-god-appearing?lang=eng&#39"],
                                56: ["Softly Beams the Sacred Dawning","https://www.churchofjesuschrist.org/music/library/hymns/softly-beams-the-sacred-dawning?lang=eng&#39"],
                             57: ["We're Not Ashamed to Own Our Lord","https://www.churchofjesuschrist.org/music/library/hymns/were-not-ashamed-to-own-our-lord?lang=eng&#39"],
                                     58: ["Come, Ye Children of the Lord","https://www.churchofjesuschrist.org/music/library/hymns/come-ye-children-of-the-lord?lang=eng&#39"],
                                           59: ["Come, O Thou King of Kings","https://www.churchofjesuschrist.org/music/library/hymns/come-o-thou-king-of-kings?lang=eng&#39"],
                                        60: ["Battle Hymn of the Republic","https://www.churchofjesuschrist.org/music/library/hymns/battle-hymn-of-the-republic?lang=eng&#39"],
                                    61: ["Raise Your Voices to the Lord","https://www.churchofjesuschrist.org/music/library/hymns/raise-your-voices-to-the-lord?lang=eng&#39"],
                            62: ["All Creatures of Our God and King","https://www.churchofjesuschrist.org/music/library/hymns/all-creatures-of-our-god-and-king?lang=eng&#39"],
                                                      63: ["Great King of Heaven","https://www.churchofjesuschrist.org/music/library/hymns/great-king-of-heaven?lang=eng&#39"],
                                64: ["On This Day of Joy and Gladness","https://www.churchofjesuschrist.org/music/library/hymns/on-this-day-of-joy-and-gladness?lang=eng&#39"],
                   65: ["Come, All Ye Saints Who Dwell on Earth","https://www.churchofjesuschrist.org/music/library/hymns/come-all-ye-saints-who-dwell-on-earth?lang=eng&#39"],
                                            66: ["Rejoice, the Lord Is King!","https://www.churchofjesuschrist.org/music/library/hymns/rejoice-the-lord-is-king?lang=eng&#39"],
                                                      67: ["Glory to God on High","https://www.churchofjesuschrist.org/music/library/hymns/glory-to-god-on-high?lang=eng&#39"],
                                      68: ["A Mighty Fortress Is Our God","https://www.churchofjesuschrist.org/music/library/hymns/a-mighty-fortress-is-our-god?lang=eng&#39"],
                                            69: ["All Glory, Laud, and Honor","https://www.churchofjesuschrist.org/music/library/hymns/all-glory-laud-and-honor?lang=eng&#39"],
                                                          70: ["Sing Praise to Him","https://www.churchofjesuschrist.org/music/library/hymns/sing-praise-to-him?lang=eng&#39"],
                                                      71: ["With Songs of Praise","https://www.churchofjesuschrist.org/music/library/hymns/with-songs-of-praise?lang=eng&#39"],
                               72: ["Praise to the Lord, the Almighty","https://www.churchofjesuschrist.org/music/library/hymns/praise-to-the-lord-the-almighty?lang=eng&#39"],
                      73: ["Praise the Lord with Heart and Voice","https://www.churchofjesuschrist.org/music/library/hymns/praise-the-lord-with-heart-and-voice?lang=eng&#39"],
                                                          74: ["Praise Ye the Lord","https://www.churchofjesuschrist.org/music/library/hymns/praise-ye-the-lord?lang=eng&#39"],
                                                          75: ["In Hymns of Praise","https://www.churchofjesuschrist.org/music/library/hymns/in-hymns-of-praise?lang=eng&#39"],
                     76: ["God of Our Fathers, We Come unto Thee","https://www.churchofjesuschrist.org/music/library/hymns/god-of-our-fathers-we-come-unto-thee?lang=eng&#39"],
                                                            77: ["Great Is the Lord","https://www.churchofjesuschrist.org/music/library/hymns/great-is-the-lord?lang=eng&#39"],
                 78: ["God of Our Fathers, Whose Almighty Hand","https://www.churchofjesuschrist.org/music/library/hymns/god-of-our-fathers-whose-almighty-hand?lang=eng&#39"],
                  79: ["With All the Power of Heart and Tongue","https://www.churchofjesuschrist.org/music/library/hymns/with-all-the-power-of-heart-and-tongue?lang=eng&#39"],
                               80: ["God of Our Fathers, Known of Old","https://www.churchofjesuschrist.org/music/library/hymns/god-of-our-fathers-known-of-old?lang=eng&#39"],
                                                     81: ["Press Forward, Saints","https://www.churchofjesuschrist.org/music/library/hymns/press-forward-saints?lang=eng&#39"],
                                                          82: ["For All the Saints","https://www.churchofjesuschrist.org/music/library/hymns/for-all-the-saints?lang=eng&#39"],
                                   83: ["Guide Us, O Thou Great Jehovah","https://www.churchofjesuschrist.org/music/library/hymns/guide-us-o-thou-great-jehovah?lang=eng&#39"],
                                                      84: ["Faith of Our Fathers","https://www.churchofjesuschrist.org/music/library/hymns/faith-of-our-fathers?lang=eng&#39"],
                                                    85: ["How Firm a Foundation","https://www.churchofjesuschrist.org/music/library/hymns/how-firm-a-foundation?lang=eng&#39"],
                                                          86: ["How Great Thou Art","https://www.churchofjesuschrist.org/music/library/hymns/how-great-thou-art?lang=eng&#39"],
                                                                        87: ["God Is Love","https://www.churchofjesuschrist.org/music/library/hymns/god-is-love?lang=eng&#39"],
                           88: ["Great God, Attend While Zion Sings","https://www.churchofjesuschrist.org/music/library/hymns/great-god-attend-while-zion-sings?lang=eng&#39"],
                                                      89: ["The Lord Is My Light","https://www.churchofjesuschrist.org/music/library/hymns/the-lord-is-my-light?lang=eng&#39"],
                        90: ["From All That Dwell below the Skies","https://www.churchofjesuschrist.org/music/library/hymns/from-all-that-dwell-below-the-skies?lang=eng&#39"],
                   91: ["Father, Thy Children to Thee Now Raise","https://www.churchofjesuschrist.org/music/library/hymns/father-thy-children-to-thee-now-raise?lang=eng&#39"],
                                        92: ["For the Beauty of the Earth","https://www.churchofjesuschrist.org/music/library/hymns/for-the-beauty-of-the-earth?lang=eng&#39"],
                                                  93: ["Prayer of Thanksgiving","https://www.churchofjesuschrist.org/music/library/hymns/prayer-of-thanksgiving?lang=eng&#39"],
                                               94: ["Come, Ye Thankful People","https://www.churchofjesuschrist.org/music/library/hymns/come-ye-thankful-people?lang=eng&#39"],
                                              95: ["Now Thank We All Our God","https://www.churchofjesuschrist.org/music/library/hymns/now-thank-we-all-our-god?lang=eng&#39"],
                             96: ["Dearest Children, God Is Near You","https://www.churchofjesuschrist.org/music/library/hymns/dearest-children-god-is-near-you?lang=eng&#39"],
                                                           97: ["Lead, Kindly Light","https://www.churchofjesuschrist.org/music/library/hymns/lead-kindly-light?lang=eng&#39"],
                                                  98: ["I Need Thee Every Hour","https://www.churchofjesuschrist.org/music/library/hymns/i-need-thee-every-hour?lang=eng&#39"],
                                        99: ["Nearer, Dear Savior, to Thee","https://www.churchofjesuschrist.org/music/library/hymns/nearer-dear-savior-to-thee?lang=eng&#39"],
                                                 100: ["Nearer, My God, to Thee","https://www.churchofjesuschrist.org/music/library/hymns/nearer-my-god-to-thee?lang=eng&#39"],
                                                             101: ["Guide Me to Thee","https://www.churchofjesuschrist.org/music/library/hymns/guide-me-to-thee?lang=eng&#39"],
                                                102: ["Jesus, Lover of My Soul","https://www.churchofjesuschrist.org/music/library/hymns/jesus-lover-of-my-soul?lang=eng&#39"],
                                  103: ["Precious Savior, Dear Redeemer","https://www.churchofjesuschrist.org/music/library/hymns/precious-savior-dear-redeemer?lang=eng&#39"],
                                                 104: ["Jesus, Savior, Pilot Me","https://www.churchofjesuschrist.org/music/library/hymns/jesus-savior-pilot-me?lang=eng&#39"],
                                    105: ["Master, the Tempest Is Raging","https://www.churchofjesuschrist.org/music/library/hymns/master-the-tempest-is-raging?lang=eng&#39"],
                                                       106: ["God Speed the Right","https://www.churchofjesuschrist.org/music/library/hymns/god-speed-the-right?lang=eng&#39"],
                                  107: ["Lord, Accept Our True Devotion","https://www.churchofjesuschrist.org/music/library/hymns/lord-accept-our-true-devotion?lang=eng&#39"],
                                               108: ["The Lord Is My Shepherd","https://www.churchofjesuschrist.org/music/library/hymns/the-lord-is-my-shepherd?lang=eng&#39"],
                             109: ["The Lord My Pasture Will Prepare","https://www.churchofjesuschrist.org/music/library/hymns/the-lord-my-pasture-will-prepare?lang=eng&#39"],
                                   110: ["Cast Thy Burden upon the Lord","https://www.churchofjesuschrist.org/music/library/hymns/cast-thy-burden-upon-the-lord?lang=eng&#39"],
                                                                     111: ["Rock of Ages","https://www.churchofjesuschrist.org/music/library/hymns/rock-of-ages?lang=eng&#39"],
                                        112: ["Savior, Redeemer of My Soul","https://www.churchofjesuschrist.org/music/library/hymns/savior-redeemer-of-my-soul?lang=eng&#39"],
                                                            113: ["Our Savior's Love","https://www.churchofjesuschrist.org/music/library/hymns/our-saviors-love?lang=eng&#39"],
                                                                   114: ["Come unto Him","https://www.churchofjesuschrist.org/music/library/hymns/come-unto-him?lang=eng&#39"],
                                                    115: ["Come, Ye Disconsolate","https://www.churchofjesuschrist.org/music/library/hymns/come-ye-disconsolate?lang=eng&#39"],
                                                                116: ["Come, Follow Me","https://www.churchofjesuschrist.org/music/library/hymns/come-follow-me?lang=eng&#39"],
                                                               117: ["Come unto Jesus","https://www.churchofjesuschrist.org/music/library/hymns/come-unto-jesus?lang=eng&#39"],
                                           118: ["Ye Simple Souls Who Stray","https://www.churchofjesuschrist.org/music/library/hymns/ye-simple-souls-who-stray?lang=eng&#39"],
                                        119: ["Come, We That Love the Lord","https://www.churchofjesuschrist.org/music/library/hymns/come-we-that-love-the-lord?lang=eng&#39"],
                                                     120: ["Lean on My Ample Arm","https://www.churchofjesuschrist.org/music/library/hymns/lean-on-my-ample-arm?lang=eng&#39"],
                                      121: ["I'm a Pilgrim, I'm a Stranger","https://www.churchofjesuschrist.org/music/library/hymns/im-a-pilgrim-im-a-stranger?lang=eng&#39"],
                                               122: ["Though Deepening Trials","https://www.churchofjesuschrist.org/music/library/hymns/though-deepening-trials?lang=eng&#39"],
                            123: ["Oh, May My Soul Commune with Thee","https://www.churchofjesuschrist.org/music/library/hymns/oh-may-my-soul-commune-with-thee?lang=eng&#39"],
                                            124: ["Be Still, My Soul",None],
                                            125: ["How Gentle God's Commands","https://www.churchofjesuschrist.org/music/library/hymns/how-gentle-gods-commands?lang=eng&#39"],
                        126: ["How Long, O Lord Most Holy and True","https://www.churchofjesuschrist.org/music/library/hymns/how-long-o-lord-most-holy-and-true?lang=eng&#39"],
                                        127: ["Does the Journey Seem Long?","https://www.churchofjesuschrist.org/music/library/hymns/does-the-journey-seem-long?lang=eng&#39"],
                                                         128: ["When Faith Endures","https://www.churchofjesuschrist.org/music/library/hymns/when-faith-endures?lang=eng&#39"],
                                        129: ["Where Can I Turn for Peace?","https://www.churchofjesuschrist.org/music/library/hymns/where-can-i-turn-for-peace?lang=eng&#39"],
                                                                 130: ["Be Thou Humble","https://www.churchofjesuschrist.org/music/library/hymns/be-thou-humble?lang=eng&#39"],
                                                   131: ["More Holiness Give Me","https://www.churchofjesuschrist.org/music/library/hymns/more-holiness-give-me?lang=eng&#39"],
                                           132: ["God Is in His Holy Temple","https://www.churchofjesuschrist.org/music/library/hymns/god-is-in-his-holy-temple?lang=eng&#39"],
                                                             133: ["Father in Heaven","https://www.churchofjesuschrist.org/music/library/hymns/father-in-heaven?lang=eng&#39"],
                                                       134: ["I Believe in Christ","https://www.churchofjesuschrist.org/music/library/hymns/i-believe-in-christ?lang=eng&#39"],
                                                           135: ["My Redeemer Lives","https://www.churchofjesuschrist.org/music/library/hymns/my-redeemer-lives?lang=eng&#39"],
                                   136: ["I Know That My Redeemer Lives","https://www.churchofjesuschrist.org/music/library/hymns/i-know-that-my-redeemer-lives?lang=eng&#39"],
                                                                           137: ["Testimony","https://www.churchofjesuschrist.org/music/library/hymns/testimony?lang=eng&#39"],
                                                138: ["Bless Our Fast, We Pray","https://www.churchofjesuschrist.org/music/library/hymns/bless-our-fast-we-pray?lang=eng&#39"],
                                       139: ["In Fasting We Approach Thee","https://www.churchofjesuschrist.org/music/library/hymns/in-fasting-we-approach-thee?lang=eng&#39"],
                                                  140: ["Did You Think to Pray?","https://www.churchofjesuschrist.org/music/library/hymns/did-you-think-to-pray?lang=eng&#39"],
                                141: ["Jesus, the Very Thought of Thee","https://www.churchofjesuschrist.org/music/library/hymns/jesus-the-very-thought-of-thee?lang=eng&#39"],
                                                     142: ["Sweet Hour of Prayer","https://www.churchofjesuschrist.org/music/library/hymns/sweet-hour-of-prayer?lang=eng&#39"],
                                           143: ["Let the Holy Spirit Guide","https://www.churchofjesuschrist.org/music/library/hymns/let-the-holy-spirit-guide?lang=eng&#39"],
                                                                   144: ["Secret Prayer","https://www.churchofjesuschrist.org/music/library/hymns/secret-prayer?lang=eng&#39"],
                        145: ["Prayer Is the Soul's Sincere Desire","https://www.churchofjesuschrist.org/music/library/hymns/prayer-is-the-souls-sincere-desire?lang=eng&#39"],
                                 146: ["Gently Raise the Sacred Strain","https://www.churchofjesuschrist.org/music/library/hymns/gently-raise-the-sacred-strain?lang=eng&#39"],
                                                           147: ["Sweet Is the Work","https://www.churchofjesuschrist.org/music/library/hymns/sweet-is-the-work?lang=eng&#39"],
                                                                       148: ["Sabbath Day","https://www.churchofjesuschrist.org/music/library/hymns/sabbath-day?lang=eng&#39"],
                           149: ["As the Dew from Heaven Distilling","https://www.churchofjesuschrist.org/music/library/hymns/as-the-dew-from-heaven-distilling?lang=eng&#39"],
                               150: ["O Thou Kind and Gracious Father","https://www.churchofjesuschrist.org/music/library/hymns/o-thou-kind-and-gracious-father?lang=eng&#39"],
                                                          151: ["We Meet, Dear Lord","https://www.churchofjesuschrist.org/music/library/hymns/we-meet-dear-lord?lang=eng&#39"],
                         152: ["God Be with You Till We Meet Again","https://www.churchofjesuschrist.org/music/library/hymns/god-be-with-you-till-we-meet-again?lang=eng&#39"],
                                    153: ["Lord, We Ask Thee Ere We Part","https://www.churchofjesuschrist.org/music/library/hymns/lord-we-ask-thee-ere-we-part?lang=eng&#39"],
                    154: ["Father, This Hour Has Been One of Joy","https://www.churchofjesuschrist.org/music/library/hymns/father-this-hour-has-been-one-of-joy?lang=eng&#39"],
                                     155: ["We Have Partaken of Thy Love","https://www.churchofjesuschrist.org/music/library/hymns/we-have-partaken-of-thy-love?lang=eng&#39"],
                                                 156: ["Sing We Now at Parting","https://www.churchofjesuschrist.org/music/library/hymns/sing-we-now-at-parting?lang=eng&#39"],
                 157: ["Thy Spirit, Lord, Has Stirred Our Souls","https://www.churchofjesuschrist.org/music/library/hymns/thy-spirit-lord-has-stirred-our-souls?lang=eng&#39"],
                               158: ["Before Thee, Lord, I Bow My Head","https://www.churchofjesuschrist.org/music/library/hymns/before-thee-lord-i-bow-my-head?lang=eng&#39"],
                                                       159: ["Now the Day Is Over","https://www.churchofjesuschrist.org/music/library/hymns/now-the-day-is-over?lang=eng&#39"],
                                       160: ["Softly Now the Light of Day","https://www.churchofjesuschrist.org/music/library/hymns/softly-now-the-light-of-day?lang=eng&#39"],
                                                       161: ["The Lord Be with Us","https://www.churchofjesuschrist.org/music/library/hymns/the-lord-be-with-us?lang=eng&#39"],
                                    162: ["Lord, We Come before Thee Now","https://www.churchofjesuschrist.org/music/library/hymns/lord-we-come-before-thee-now?lang=eng&#39"],
                          163: ["Lord, Dismiss Us with Thy Blessing","https://www.churchofjesuschrist.org/music/library/hymns/lord-dismiss-us-with-thy-blessing?lang=eng&#39"],
                          164: ["Great God, to Thee My Evening Song","https://www.churchofjesuschrist.org/music/library/hymns/great-god-to-thee-my-evening-song?lang=eng&#39"],
                                        165: ["Abide with Me 'Tis Eventide","https://www.churchofjesuschrist.org/music/library/hymns/abide-with-me-tis-eventide?lang=eng&#39"],
                                                                  166: ["Abide with Me!","https://www.churchofjesuschrist.org/music/library/hymns/abide-with-me?lang=eng&#39"],
                            167: ["Come, Let Us Sing an Evening Hymn","https://www.churchofjesuschrist.org/music/library/hymns/come-let-us-sing-an-evening-hymn?lang=eng&#39"],
                                                       168: ["As the Shadows Fall","https://www.churchofjesuschrist.org/music/library/hymns/as-the-shadows-fall?lang=eng&#39"],
                                     169: ["As Now We Take the Sacrament","https://www.churchofjesuschrist.org/music/library/hymns/as-now-we-take-the-sacrament?lang=eng&#39"],
                                     170: ["God, Our Father, Hear Us Pray","https://www.churchofjesuschrist.org/music/library/hymns/god-our-father-hear-us-pray?lang=eng&#39"],
                                                           171: ["With Humble Heart","https://www.churchofjesuschrist.org/music/library/hymns/with-humble-heart?lang=eng&#39"],
                                                172: ["In Humility, Our Savior","https://www.churchofjesuschrist.org/music/library/hymns/in-humility-our-savior?lang=eng&#39"],
                      173: ["While of These Emblems We Partake","https://www.churchofjesuschrist.org/music/library/hymns/while-of-these-emblems-we-partake-saul?lang=eng&#39"],
                   174: ["While of These Emblems We Partake","https://www.churchofjesuschrist.org/music/library/hymns/while-of-these-emblems-we-partake-aeolian?lang=eng&#39"],
                                            175: ["O God, the Eternal Father","https://www.churchofjesuschrist.org/music/library/hymns/o-god-the-eternal-father?lang=eng&#39"],
            176: ["Tis Sweet to Sing the Matchless Love","https://www.churchofjesuschrist.org/music/library/hymns/tis-sweet-to-sing-the-matchless-love-meredith?lang=eng&#39"],
             177: ["Tis Sweet to Sing the Matchless Love","https://www.churchofjesuschrist.org/music/library/hymns/tis-sweet-to-sing-the-matchless-love-hancock?lang=eng&#39"],
                                                               178: ["O Lord of Hosts","https://www.churchofjesuschrist.org/music/library/hymns/o-lord-of-hosts?lang=eng&#39"],
                                  179: ["Again, Our Dear Redeeming Lord","https://www.churchofjesuschrist.org/music/library/hymns/again-our-dear-redeeming-lord?lang=eng&#39"],
                                180: ["Father in Heaven, We Do Believe","https://www.churchofjesuschrist.org/music/library/hymns/father-in-heaven-we-do-believe?lang=eng&#39"],
                          181: ["Jesus of Nazareth, Savior and King","https://www.churchofjesuschrist.org/music/library/hymns/jesus-of-nazareth-savior-and-king?lang=eng&#39"],
                           182: ["We'll Sing All Hail to Jesus' Name","https://www.churchofjesuschrist.org/music/library/hymns/well-sing-all-hail-to-jesus-name?lang=eng&#39"],
                               183: ["In Remembrance of Thy Suffering","https://www.churchofjesuschrist.org/music/library/hymns/in-remembrance-of-thy-suffering?lang=eng&#39"],
                                           184: ["Upon the Cross of Calvary","https://www.churchofjesuschrist.org/music/library/hymns/upon-the-cross-of-calvary?lang=eng&#39"],
                                           185: ["Reverently and Meekly Now","https://www.churchofjesuschrist.org/music/library/hymns/reverently-and-meekly-now?lang=eng&#39"],
                                 186: ["Again We Meet around the Board","https://www.churchofjesuschrist.org/music/library/hymns/again-we-meet-around-the-board?lang=eng&#39"],
                              187: ["God Loved Us, So He Sent His Son","https://www.churchofjesuschrist.org/music/library/hymns/god-loved-us-so-he-sent-his-son?lang=eng&#39"],
                                             188: ["Thy Will, O Lord, Be Done","https://www.churchofjesuschrist.org/music/library/hymns/thy-will-o-lord-be-done?lang=eng&#39"],
                                  189: ["O Thou, Before the World Began","https://www.churchofjesuschrist.org/music/library/hymns/o-thou-before-the-world-began?lang=eng&#39"],
                                         190: ["In Memory of the Crucified","https://www.churchofjesuschrist.org/music/library/hymns/in-memory-of-the-crucified?lang=eng&#39"],
                                   191: ["Behold the Great Redeemer Die","https://www.churchofjesuschrist.org/music/library/hymns/behold-the-great-redeemer-die?lang=eng&#39"],
                              192: ["He Died! The Great Redeemer Died","https://www.churchofjesuschrist.org/music/library/hymns/he-died-the-great-redeemer-died?lang=eng&#39"],
                                                         193: ["I Stand All Amazed","https://www.churchofjesuschrist.org/music/library/hymns/i-stand-all-amazed?lang=eng&#39"],
                                 194: ["There Is a Green Hill Far Away","https://www.churchofjesuschrist.org/music/library/hymns/there-is-a-green-hill-far-away?lang=eng&#39"],
                           195: ["How Great the Wisdom and the Love","https://www.churchofjesuschrist.org/music/library/hymns/how-great-the-wisdom-and-the-love?lang=eng&#39"],
                                        196: ["Jesus, Once of Humble Birth","https://www.churchofjesuschrist.org/music/library/hymns/jesus-once-of-humble-birth?lang=eng&#39"],
                          197: ["O Savior, Thou Who Wearest a Crown","https://www.churchofjesuschrist.org/music/library/hymns/o-savior-thou-who-wearest-a-crown?lang=eng&#39"],
                                                             198: ["That Easter Morn","https://www.churchofjesuschrist.org/music/library/hymns/that-easter-morn?lang=eng&#39"],
                                                                      199: ["He Is Risen!","https://www.churchofjesuschrist.org/music/library/hymns/he-is-risen?lang=eng&#39"],
                                 200: ["Christ the Lord Is Risen Today","https://www.churchofjesuschrist.org/music/library/hymns/christ-the-lord-is-risen-today?lang=eng&#39"],
                                                             201: ["Joy to the World","https://www.churchofjesuschrist.org/music/library/hymns/joy-to-the-world?lang=eng&#39"],
                                             202: ["Oh, Come, All Ye Faithful","https://www.churchofjesuschrist.org/music/library/hymns/oh-come-all-ye-faithful?lang=eng&#39"],
                                     203: ["Angels We Have Heard on High","https://www.churchofjesuschrist.org/music/library/hymns/angels-we-have-heard-on-high?lang=eng&#39"],
                                                                     204: ["Silent Night","https://www.churchofjesuschrist.org/music/library/hymns/silent-night?lang=eng&#39"],
                                          205: ["Once in Royal David's City","https://www.churchofjesuschrist.org/music/library/hymns/once-in-royal-davids-city?lang=eng&#39"],
                                                             206: ["Away in a Manger","https://www.churchofjesuschrist.org/music/library/hymns/away-in-a-manger?lang=eng&#39"],
                               207: ["It Came upon the Midnight Clear","https://www.churchofjesuschrist.org/music/library/hymns/it-came-upon-the-midnight-clear?lang=eng&#39"],
                                         208: ["O Little Town of Bethlehem","https://www.churchofjesuschrist.org/music/library/hymns/o-little-town-of-bethlehem?lang=eng&#39"],
                                      209: ["Hark! The Herald Angels Sing","https://www.churchofjesuschrist.org/music/library/hymns/hark-the-herald-angels-sing?lang=eng&#39"],
                                                         210: ["With Wondering Awe","https://www.churchofjesuschrist.org/music/library/hymns/with-wondering-awe?lang=eng&#39"],
                     211: ["While Shepherds Watched Their Flocks","https://www.churchofjesuschrist.org/music/library/hymns/while-shepherds-watched-their-flocks?lang=eng&#39"],
                                 212: ["Far, Far Away on Judea's Plains","https://www.churchofjesuschrist.org/music/library/hymns/far-far-away-on-judeas-plains?lang=eng&#39"],
                                                                 213: ["The First Noel","https://www.churchofjesuschrist.org/music/library/hymns/the-first-noel?lang=eng&#39"],
                         214: ["I Heard the Bells on Christmas Day","https://www.churchofjesuschrist.org/music/library/hymns/i-heard-the-bells-on-christmas-day?lang=eng&#39"],
                                                      215: ["Ring Out, Wild Bells","https://www.churchofjesuschrist.org/music/library/hymns/ring-out-wild-bells?lang=eng&#39"],
                                                                   216: ["We Are Sowing","https://www.churchofjesuschrist.org/music/library/hymns/we-are-sowing?lang=eng&#39"],
                                                            217: ["Come, Let Us Anew","https://www.churchofjesuschrist.org/music/library/hymns/come-let-us-anew?lang=eng&#39"],
                                         218: ["We Give Thee But Thine Own","https://www.churchofjesuschrist.org/music/library/hymns/we-give-thee-but-thine-own?lang=eng&#39"],
                                 219: ["Because I Have Been Given Much","https://www.churchofjesuschrist.org/music/library/hymns/because-i-have-been-given-much?lang=eng&#39"],
                                            220: ["Lord, I Would Follow Thee","https://www.churchofjesuschrist.org/music/library/hymns/lord-i-would-follow-thee?lang=eng&#39"],
                           221: ["Dear to the Heart of the Shepherd","https://www.churchofjesuschrist.org/music/library/hymns/dear-to-the-heart-of-the-shepherd?lang=eng&#39"],
                                          222: ["Hear Thou Our Hymn, O Lord","https://www.churchofjesuschrist.org/music/library/hymns/hear-thou-our-hymn-o-lord?lang=eng&#39"],
                                                    223: ["Have I Done Any Good?","https://www.churchofjesuschrist.org/music/library/hymns/have-i-done-any-good?lang=eng&#39"],
                                             224: ["I Have Work Enough to Do","https://www.churchofjesuschrist.org/music/library/hymns/i-have-work-enough-to-do?lang=eng&#39"],
                                       225: ["We Are Marching On to Glory","https://www.churchofjesuschrist.org/music/library/hymns/we-are-marching-on-to-glory?lang=eng&#39"],
                                       226: ["Improve the Shining Moments","https://www.churchofjesuschrist.org/music/library/hymns/improve-the-shining-moments?lang=eng&#39"],
                         227: ["There Is Sunshine in My Soul Today","https://www.churchofjesuschrist.org/music/library/hymns/there-is-sunshine-in-my-soul-today?lang=eng&#39"],
                               228: ["You Can Make the Pathway Bright","https://www.churchofjesuschrist.org/music/library/hymns/you-can-make-the-pathway-bright?lang=eng&#39"],
                                        229: ["Today, While the Sun Shines","https://www.churchofjesuschrist.org/music/library/hymns/today-while-the-sun-shines?lang=eng&#39"],
                                                             230: ["Scatter Sunshine","https://www.churchofjesuschrist.org/music/library/hymns/scatter-sunshine?lang=eng&#39"],
                                231: ["Father, Cheer Our Souls Tonight","https://www.churchofjesuschrist.org/music/library/hymns/father-cheer-our-souls-tonight?lang=eng&#39"],
                                       232: ["Let Us Oft Speak Kind Words","https://www.churchofjesuschrist.org/music/library/hymns/let-us-oft-speak-kind-words?lang=eng&#39"],
                                                            233: ["Nay, Speak No Ill","https://www.churchofjesuschrist.org/music/library/hymns/nay-speak-no-ill?lang=eng&#39"],
                                          234: ["Jesus, Mighty King in Zion","https://www.churchofjesuschrist.org/music/library/hymns/jesus-mighty-king-in-zion?lang=eng&#39"],
                       235: ["Should You Feel Inclined to Censure","https://www.churchofjesuschrist.org/music/library/hymns/should-you-feel-inclined-to-censure?lang=eng&#39"],
                                    236: ["Lord, Accept into Thy Kingdom","https://www.churchofjesuschrist.org/music/library/hymns/lord-accept-into-thy-kingdom?lang=eng&#39"],
                                                             237: ["Do What Is Right","https://www.churchofjesuschrist.org/music/library/hymns/do-what-is-right?lang=eng&#39"],
                        238: ["Behold Thy Sons and Daughters, Lord","https://www.churchofjesuschrist.org/music/library/hymns/behold-thy-sons-and-daughters-lord?lang=eng&#39"],
                                                             239: ["Choose the Right","https://www.churchofjesuschrist.org/music/library/hymns/choose-the-right?lang=eng&#39"],
                          240: ["Know This, That Every Soul Is Free","https://www.churchofjesuschrist.org/music/library/hymns/know-this-that-every-soul-is-free?lang=eng&#39"],
                                                     241: ["Count Your Blessings","https://www.churchofjesuschrist.org/music/library/hymns/count-your-blessings?lang=eng&#39"],
              242: ["Praise God, from Whom All Blessings Flow","https://www.churchofjesuschrist.org/music/library/hymns/praise-god-from-whom-all-blessings-flow?lang=eng&#39"],
                                                       243: ["Let Us All Press On","https://www.churchofjesuschrist.org/music/library/hymns/let-us-all-press-on?lang=eng&#39"],
                                                  244: ["Come Along, Come Along","https://www.churchofjesuschrist.org/music/library/hymns/come-along-come-along?lang=eng&#39"],
                                 245: ["This House We Dedicate to Thee","https://www.churchofjesuschrist.org/music/library/hymns/this-house-we-dedicate-to-thee?lang=eng&#39"],
                                          246: ["Onward, Christian Soldiers","https://www.churchofjesuschrist.org/music/library/hymns/onward-christian-soldiers?lang=eng&#39"],
                                              247: ["We Love Thy House, O God","https://www.churchofjesuschrist.org/music/library/hymns/we-love-thy-house-o-god?lang=eng&#39"],
                                 248: ["Up, Awake, Ye Defenders of Zion","https://www.churchofjesuschrist.org/music/library/hymns/up-awake-ye-defenders-of-zion?lang=eng&#39"],
                                                               249: ["Called to Serve","https://www.churchofjesuschrist.org/music/library/hymns/called-to-serve?lang=eng&#39"],
                                                       250: ["We Are All Enlisted","https://www.churchofjesuschrist.org/music/library/hymns/we-are-all-enlisted?lang=eng&#39"],
                                                      251: ["Behold! A Royal Army","https://www.churchofjesuschrist.org/music/library/hymns/behold-a-royal-army?lang=eng&#39"],
                                 252: ["Put Your Shoulder to the Wheel","https://www.churchofjesuschrist.org/music/library/hymns/put-your-shoulder-to-the-wheel?lang=eng&#39"],
                         253: ["Like Ten Thousand Legions Marching","https://www.churchofjesuschrist.org/music/library/hymns/like-ten-thousand-legions-marching?lang=eng&#39"],
                                                           254: ["True to the Faith","https://www.churchofjesuschrist.org/music/library/hymns/true-to-the-faith?lang=eng&#39"],
                                                                             255: ["Carry On","https://www.churchofjesuschrist.org/music/library/hymns/carry-on?lang=eng&#39"],
                                  256: ["As Zion's Youth in Latter Days","https://www.churchofjesuschrist.org/music/library/hymns/as-zions-youth-in-latter-days?lang=eng&#39"],
                          257: ["Rejoice! A Glorious Sound Is Heard","https://www.churchofjesuschrist.org/music/library/hymns/rejoice-a-glorious-sound-is-heard?lang=eng&#39"],
                                     258: ["O Thou Rock of Our Salvation","https://www.churchofjesuschrist.org/music/library/hymns/o-thou-rock-of-our-salvation?lang=eng&#39"],
                                                                 259: ["Hope of Israel","https://www.churchofjesuschrist.org/music/library/hymns/hope-of-israel?lang=eng&#39"],
                                              260: ["Who's on the Lord's Side?","https://www.churchofjesuschrist.org/music/library/hymns/whos-on-the-lords-side?lang=eng&#39"],
                                           261: ["Thy Servants Are Prepared","https://www.churchofjesuschrist.org/music/library/hymns/thy-servants-are-prepared?lang=eng&#39"],
                                          262: ["Go, Ye Messengers of Glory","https://www.churchofjesuschrist.org/music/library/hymns/go-ye-messengers-of-glory?lang=eng&#39"],
                                                       263: ["Go Forth with Faith","https://www.churchofjesuschrist.org/music/library/hymns/go-forth-with-faith?lang=eng&#39"],
                                                     264: ["Hark, All Ye Nations!","https://www.churchofjesuschrist.org/music/library/hymns/hark-all-ye-nations?lang=eng&#39"],
                                                 265: ["Arise, O God, and Shine","https://www.churchofjesuschrist.org/music/library/hymns/arise-o-god-and-shine?lang=eng&#39"],
                                                   266: ["The Time Is Far Spent","https://www.churchofjesuschrist.org/music/library/hymns/the-time-is-far-spent?lang=eng&#39"],
                                                 267: ["How Wondrous and Great","https://www.churchofjesuschrist.org/music/library/hymns/how-wondrous-and-great?lang=eng&#39"],
                            268: ["Come, All Whose Souls Are Lighted","https://www.churchofjesuschrist.org/music/library/hymns/come-all-whose-souls-are-lighted?lang=eng&#39"],
                            269: ["Jehovah, Lord of Heaven and Earth","https://www.churchofjesuschrist.org/music/library/hymns/jehovah-lord-of-heaven-and-earth?lang=eng&#39"],
                                270: ["I'll Go Where You Want Me to Go","https://www.churchofjesuschrist.org/music/library/hymns/ill-go-where-you-want-me-to-go?lang=eng&#39"],
                              271: ["Oh, Holy Words of Truth and Love","https://www.churchofjesuschrist.org/music/library/hymns/oh-holy-words-of-truth-and-love?lang=eng&#39"],
                                                   272: ["Oh Say, What Is Truth?","https://www.churchofjesuschrist.org/music/library/hymns/oh-say-what-is-truth?lang=eng&#39"],
                                 273: ["Truth Reflects upon Our Senses","https://www.churchofjesuschrist.org/music/library/hymns/truth-reflects-upon-our-senses?lang=eng&#39"],
                                                                     274: ["The Iron Rod","https://www.churchofjesuschrist.org/music/library/hymns/the-iron-rod?lang=eng&#39"],
                             275: ["Men Are That They Might Have Joy","https://www.churchofjesuschrist.org/music/library/hymns/men-are-that-they-might-have-joy?lang=eng&#39"],
                                 276: ["Come Away to the Sunday School","https://www.churchofjesuschrist.org/music/library/hymns/come-away-to-the-sunday-school?lang=eng&#39"],
                               277: ["As I Search the Holy Scriptures","https://www.churchofjesuschrist.org/music/library/hymns/as-i-search-the-holy-scriptures?lang=eng&#39"],
                                   278: ["Thanks for the Sabbath School","https://www.churchofjesuschrist.org/music/library/hymns/thanks-for-the-sabbath-school?lang=eng&#39"],
                                                                   279: ["Thy Holy Word","https://www.churchofjesuschrist.org/music/library/hymns/thy-holy-word?lang=eng&#39"],
                             280: ["Welcome, Welcome, Sabbath Morning","https://www.churchofjesuschrist.org/music/library/hymns/welcome-welcome-sabbath-morning?lang=eng&#39"],
                                 281: ["Help Me Teach with Inspiration","https://www.churchofjesuschrist.org/music/library/hymns/help-me-teach-with-inspiration?lang=eng&#39"],
                               282: ["We Meet Again in Sabbath School","https://www.churchofjesuschrist.org/music/library/hymns/we-meet-again-in-sabbath-school?lang=eng&#39"],
                       283: ["The Glorious Gospel Light Has Shone","https://www.churchofjesuschrist.org/music/library/hymns/the-glorious-gospel-light-has-shone?lang=eng&#39"],
                                           284: ["If You Could Hie to Kolob","https://www.churchofjesuschrist.org/music/library/hymns/if-you-could-hie-to-kolob?lang=eng&#39"],
                                   285: ["God Moves in a Mysterious Way","https://www.churchofjesuschrist.org/music/library/hymns/god-moves-in-a-mysterious-way?lang=eng&#39"],
                                        286: ["Oh, What Songs of the Heart","https://www.churchofjesuschrist.org/music/library/hymns/oh-what-songs-of-the-heart?lang=eng&#39"],
                           287: ["Rise, Ye Saints, and Temples Enter","https://www.churchofjesuschrist.org/music/library/hymns/rise-ye-saints-and-temples-enter?lang=eng&#39"],
                                288: ["How Beautiful Thy Temples, Lord","https://www.churchofjesuschrist.org/music/library/hymns/how-beautiful-thy-temples-lord?lang=eng&#39"],
                                         289: ["Holy Temples on Mount Zion","https://www.churchofjesuschrist.org/music/library/hymns/holy-temples-on-mount-zion?lang=eng&#39"],
                            290: ["Rejoice, Ye Saints of Latter Days","https://www.churchofjesuschrist.org/music/library/hymns/rejoice-ye-saints-of-latter-days?lang=eng&#39"],
                                                             291: ["Turn Your Hearts","https://www.churchofjesuschrist.org/music/library/hymns/turn-your-hearts?lang=eng&#39"],
                                                                       292: ["O My Father","https://www.churchofjesuschrist.org/music/library/hymns/o-my-father?lang=eng&#39"],
                     293: ["Each Life That Touches Ours for Good","https://www.churchofjesuschrist.org/music/library/hymns/each-life-that-touches-ours-for-good?lang=eng&#39"],
                                                                     294: ["Love at Home","https://www.churchofjesuschrist.org/music/library/hymns/love-at-home?lang=eng&#39"],
                                   295: ["O Love That Glorifies the Son","https://www.churchofjesuschrist.org/music/library/hymns/o-love-that-glorifies-the-son?lang=eng&#39"],
                                            296: ["Our Father, by Whose Name","https://www.churchofjesuschrist.org/music/library/hymns/our-father-by-whose-name?lang=eng&#39"],
                   297: ["From Homes of Saints Glad Songs Arise","https://www.churchofjesuschrist.org/music/library/hymns/from-homes-of-saints-glad-songs-arise?lang=eng&#39"],
                                   298: ["Home Can Be a Heaven on Earth","https://www.churchofjesuschrist.org/music/library/hymns/home-can-be-a-heaven-on-earth?lang=eng&#39"],
                               299: ["Children of Our Heavenly Father","https://www.churchofjesuschrist.org/music/library/hymns/children-of-our-heavenly-father?lang=eng&#39"],
                             300: ["Families Can Be Together Forever","https://www.churchofjesuschrist.org/music/library/hymns/families-can-be-together-forever?lang=eng&#39"],
                                                       301: ["I Am a Child of God","https://www.churchofjesuschrist.org/music/library/hymns/i-am-a-child-of-god?lang=eng&#39"],
                                                 302: ["I Know My Father Lives","https://www.churchofjesuschrist.org/music/library/hymns/i-know-my-father-lives?lang=eng&#39"],
                                                   303: ["Keep the Commandments","https://www.churchofjesuschrist.org/music/library/hymns/keep-the-commandments?lang=eng&#39"],
                                   304: ["Teach Me to Walk in the Light","https://www.churchofjesuschrist.org/music/library/hymns/teach-me-to-walk-in-the-light?lang=eng&#39"],
                                                             305: ["The Light Divine","https://www.churchofjesuschrist.org/music/library/hymns/the-light-divine?lang=eng&#39"],
                                                              306: ["God's Daily Care","https://www.churchofjesuschrist.org/music/library/hymns/gods-daily-care?lang=eng&#39"],
                                                   307: ["In Our Lovely Deseret","https://www.churchofjesuschrist.org/music/library/hymns/in-our-lovely-deseret?lang=eng&#39"],
                                                             308: ["Love One Another","https://www.churchofjesuschrist.org/music/library/hymns/love-one-another?lang=eng&#39"],
                                           309: ["As Sisters in Zion (Women)","https://www.churchofjesuschrist.org/music/library/hymns/as-sisters-in-zion-women?lang=eng&#39"],
                 310: ["A Key Was Turned in Latter Days (Women)","https://www.churchofjesuschrist.org/music/library/hymns/a-key-was-turned-in-latter-days-women?lang=eng&#39"],
                               311: ["We Meet Again as Sisters (Women)","https://www.churchofjesuschrist.org/music/library/hymns/we-meet-again-as-sisters-women?lang=eng&#39"],
                                     312: ["We Ever Pray for Thee (Women)","https://www.churchofjesuschrist.org/music/library/hymns/we-ever-pray-for-thee-women?lang=eng&#39"],
                                                         313: ["God Is Love (Women)","https://www.churchofjesuschrist.org/music/library/hymns/god-is-love-women?lang=eng&#39"],
                              314: ["How Gentle God's Commands (Women)","https://www.churchofjesuschrist.org/music/library/hymns/how-gentle-gods-commands-women?lang=eng&#39"],
                  315: ["Jesus, the Very Thought of Thee (Women)","https://www.churchofjesuschrist.org/music/library/hymns/jesus-the-very-thought-of-thee-women?lang=eng&#39"],
                                 316: ["The Lord Is My Shepherd (Women)","https://www.churchofjesuschrist.org/music/library/hymns/the-lord-is-my-shepherd-women?lang=eng&#39"],
                                             317: ["Sweet Is the Work (Women)","https://www.churchofjesuschrist.org/music/library/hymns/sweet-is-the-work-women?lang=eng&#39"],
                                                       318: ["Love at Home (Women)","https://www.churchofjesuschrist.org/music/library/hymns/love-at-home-women?lang=eng&#39"],
                                             319: ["Ye Elders of Israel (Men)","https://www.churchofjesuschrist.org/music/library/hymns/ye-elders-of-israel-men?lang=eng&#39"],
                               320: ["The Priesthood of Our Lord (Men)","https://www.churchofjesuschrist.org/music/library/hymns/the-priesthood-of-our-lord-men?lang=eng&#39"],
                               321: ["Ye Who Are Called to Labor (Men)","https://www.churchofjesuschrist.org/music/library/hymns/ye-who-are-called-to-labor-men?lang=eng&#39"],
                                    322: ["Come, All Ye Sons of God (Men)","https://www.churchofjesuschrist.org/music/library/hymns/come-all-ye-sons-of-god-men?lang=eng&#39"],
                           323: ["Rise Up, O Men of God (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/rise-up-o-men-of-god-mens-choir?lang=eng&#39"],
                                          324: ["Rise Up, O Men of God (Men)","https://www.churchofjesuschrist.org/music/library/hymns/rise-up-o-men-of-god-men?lang=eng&#39"],
325: ["See the Mighty Priesthood Gathered (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/see-the-mighty-priesthood-gathered-mens-choir?lang=eng&#39"],
                            326: ["Come, Come, Ye Saints (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/come-come-ye-saints-mens-choir?lang=eng&#39"],
               327: ["Go, Ye Messengers of Heaven (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/go-ye-messengers-of-heaven-mens-choir?lang=eng&#39"],
                          328: ["An Angel from on High (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/an-angel-from-on-high-mens-choir?lang=eng&#39"],
                  329: ["Thy Servants Are Prepared (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/thy-servants-are-prepared-mens-choir?lang=eng&#39"],
             330: ["See, the Mighty Angel Flying (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/see-the-mighty-angel-flying-mens-choir?lang=eng&#39"],
                          331: ["Oh Say, What Is Truth? (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/oh-say-what-is-truth-mens-choir?lang=eng&#39"],
                 332: ["Come, O Thou King of Kings (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/come-o-thou-king-of-kings-mens-choir?lang=eng&#39"],
                    333: ["High on the Mountain Top (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/high-on-the-mountain-top-mens-choir?lang=eng&#39"],
                        334: ["I Need Thee Every Hour (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/i-need-thee-every-hour-mens-choir?lang=eng&#39"],
   335: ["Brightly Beams Our Father's Mercy (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/brightly-beams-our-fathers-mercy-mens-choir?lang=eng&#39"],
                              336: ["School Thy Feelings (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/school-thy-feelings-mens-choir?lang=eng&#39"],
                                        337: ["O Home Beloved (Men's Choir)","https://www.churchofjesuschrist.org/music/library/hymns/o-home-beloved-mens-choir?lang=eng&#39"],
                                                   338: ["America the Beautiful","https://www.churchofjesuschrist.org/music/library/hymns/america-the-beautiful?lang=eng&#39"],
                                               339: ["My Country, 'Tis of Thee","https://www.churchofjesuschrist.org/music/library/hymns/my-country-tis-of-thee?lang=eng&#39"],
                                             340: ["The Star-Spangled Banner","https://www.churchofjesuschrist.org/music/library/hymns/the-star-spangled-banner?lang=eng&#39"],
            341: ["God Save the King","https://www.churchofjesuschrist.org/music/library/hymns/god-save-the-king?lang=eng&#39"],
            
            1001: ["Come, Thou Fount of Every Blessing","https://www.churchofjesuschrist.org/media/music/songs/come-thou-fount-of-every-blessing?crumbs=hymns-for-home-and-church&lang=eng"],
            1002: ["When the Savior Comes Again","https://www.churchofjesuschrist.org/media/music/songs/when-the-savior-comes-again?crumbs=hymns-for-home-and-church&lang=eng"],
            1003: ["It Is Well with My Soul","https://www.churchofjesuschrist.org/media/music/songs/it-is-well-with-my-soul?crumbs=hymns-for-home-and-church&lang=eng"],
            1004: ["I Will Walk with Jesus","https://www.churchofjesuschrist.org/media/music/songs/i-will-walk-with-jesus?crumbs=hymns-for-home-and-church&lang=eng"],   
            1005: ["His Eye Is on the Sparrow","https://www.churchofjesuschrist.org/media/music/songs/his-eye-is-on-the-sparrow?crumbs=hymns-for-home-and-church&lang=eng"], 
            1006: ["Think a Sacred Song","https://www.churchofjesuschrist.org/media/music/songs/think-a-sacred-song?crumbs=hymns-for-home-and-church&lang=eng"], 
            1007: ["As Bread Is Broken","https://www.churchofjesuschrist.org/media/music/songs/as-bread-is-broken?crumbs=hymns-for-home-and-church&lang=eng"], 
            1008: ["Bread of Life, Living Water","https://www.churchofjesuschrist.org/media/music/songs/bread-of-life-living-water?crumbs=hymns-for-home-and-church&lang=eng"],                                                  
            1009: ["Gethsemane","https://www.churchofjesuschrist.org/media/music/songs/gethsemane?crumbs=hymns-for-home-and-church&lang=eng"], 
            1010: ["Amazing Grace","https://www.churchofjesuschrist.org/media/music/songs/amazing-grace?crumbs=hymns-for-home-and-church&lang=eng"],
            1011: ["Holding Hands Around the World","https://www.churchofjesuschrist.org/media/music/songs/holding-hands-around-the-world?crumbs=hymns-for-home-and-church&lang=eng"],
            1012: ["Anytime Anywhere","https://www.churchofjesuschrist.org/media/music/songs/anytime-anywhere?crumbs=hymns-for-home-and-church&lang=eng"],
            1013: ["God's Gracious Love","https://www.churchofjesuschrist.org/media/music/songs/gods-gracious-love?crumbs=hymns-for-home-and-church&lang=eng"],
            1014: ["My Shepherd Will Supply My Need","https://www.churchofjesuschrist.org/media/music/songs/my-shepherd-will-supply-my-need?crumbs=hymns-for-home-and-church&lang=eng"],
            1015: ["Oh the Deep Deep Love of Jesus","https://www.churchofjesuschrist.org/media/music/songs/oh-the-deep-deep-love-of-jesus?crumbs=hymns-for-home-and-church&lang=eng"],
            1016: ["Behold The Wounds in Jesus Hands","https://www.churchofjesuschrist.org/media/music/songs/behold-the-wounds-in-jesus-hands?crumbs=hymns-for-home-and-church&lang=eng"],
            1017: ["This Is the Christ","https://www.churchofjesuschrist.org/media/music/songs/this-is-the-christ?crumbs=hymns-for-home-and-church&lang=eng"],
            1018: ["Come Lord Jesus","https://www.churchofjesuschrist.org/media/music/songs/come-lord-jesus?crumbs=hymns-for-home-and-church&lang=eng"],
            1019: [ "To Love like Thee", "https://www.churchofjesuschrist.org/media/music/songs/to-love-like-thee-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1020: [ "Softly and Tenderly Jesus Is Calling", "https://www.churchofjesuschrist.org/media/music/songs/softly-and-tenderly-jesus-is-calling-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1021: [ "I Know That My Savior Loves Me", "https://www.churchofjesuschrist.org/media/music/songs/i-know-that-my-savior-loves-me-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1022: [ "Faith in Every Footstep", "https://www.churchofjesuschrist.org/media/music/songs/faith-in-every-footstep-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1023: [ "Standing on the Promises", "https://www.churchofjesuschrist.org/media/music/songs/standing-on-the-promises-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1024: [ "I Have Faith in The Lord Jesus Christ", "https://www.churchofjesuschrist.org/media/music/songs/i-have-faith-in-the-lord-jesus-christ-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1025: [ "Take My Heart and Let It Be Consecrated", "https://www.churchofjesuschrist.org/media/music/songs/take-my-heart-and-let-it-be-consecrated-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1026: [ "Holy Places", "https://www.churchofjesuschrist.org/media/music/songs/holy-places-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1027: [ "Welcome Home", "https://www.churchofjesuschrist.org/media/music/songs/welcome-home-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1028: [ "This Little Light of Mine", "https://www.churchofjesuschrist.org/media/music/songs/this-little-light-of-mine-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1029: [ "I Can't Count Them All", "https://www.churchofjesuschrist.org/media/music/songs/i-cant-count-them-all-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1030: [ "Close as a Quiet Prayer", "https://www.churchofjesuschrist.org/media/music/songs/close-as-a-quiet-prayer-release-3?crumbs=hymns-for-home-and-church&lang=eng"],
            1031: [ "Come, Hear the Word the Lord Has Spoken", "https://www.churchofjesuschrist.org/media/music/songs/come-hear-the-word-the-lord-has-spoken-release-3?crumbs=hymns-for-home-and-church&lang=eng"],


            1201: ["Hail the Day That Sees Him Rise","https://www.churchofjesuschrist.org/media/music/songs/hail-the-day-that-sees-him-rise?crumbs=hymns-for-home-and-church&lang=eng"], 
            1202: ["He Is Born, the Divine Christ Child","https://www.churchofjesuschrist.org/media/music/songs/he-is-born-the-divine-christ-child?crumbs=hymns-for-home-and-church&lang=eng"],
            1203: ["What Child Is This?","https://www.churchofjesuschrist.org/media/music/songs/what-child-is-this?crumbs=hymns-for-home-and-church&lang=eng"],
            1204: ["Star Bright","https://www.churchofjesuschrist.org/media/music/songs/star-bright?crumbs=hymns-for-home-and-church&lang=eng"],
            
            9999: ["Dejlig er den himmel blaa","https://www.folkekirken.dk/om-troen/salmer/dejlig-er-den-himmel-blaa"]

}